### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by aoighost** [nsacyber/WALKOFF#234]
Improving the documentation to demonstrate data being passed between apps, showing automation of execution of apps taking one piece of data and automating execution of workflows that build from there, as well as explaining internals of how it works would be useful.

An example would be showing taking a log input, seeing an ip from the logs, and then scanning it with nmap.

**Comment by adpham95** [comment]
Absolutely. We're currently holding off a bit on a documentation push as the next couple sprints will bring some UI changes and app/workflow development improvements, so much of it would need refreshing after that anyways.

**Comment by aoighost** [comment]
Fair enough, I had a distinct feeling you guys were in the middle of that. Out of curiosity, what are the sprints?

**Comment by adpham95** [comment]
The main one is adding an app editor which would allow users to edit/update/build apps from the web UI (gated behind RBAC, of course). 

Going in hand with that will be allowing more granular permissions at the individual resource level instead of just on the endpoint. (i.e. a user can execute workflows a and b, but not x and y, as opposed to the current system where they just have permissions on workflows in general.)

**Comment by aoighost** [comment]
Sweet, that will prove useful.

**Comment by emrodas10** [comment]
Closing this issue as we have updated the read the docs. We're aware that we need to update the github.io page as well as cleaning up the readme and adding a link to a swagger page for updated API endpoints.
